version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=iot
      - POSTGRES_DB=homeautomation
      - POSTGRES_PASSWORD=iot
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  influxdb:
    image: influxdb:2.0
    restart: always
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
      - DOCKER_INFLUXDB_INIT_ORG=myorg
      - DOCKER_INFLUXDB_INIT_BUCKET=mybucket
      - DOCKER_INFLUXDB_INIT_RETENTION=1w
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=mytoken
    ports:
      - '8086:8086'
    volumes:
      - influxdb:/var/lib/influxdb2

volumes:
  db:
    driver: local
  influxdb:
    driver: local
