// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/trading/holings": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "holings"
                ],
                "summary": "Get all holings",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/smartapigo.Holding"
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "smartapigo.Holding": {
            "type": "object",
            "properties": {
                "authorisedquantity": {
                    "type": "number"
                },
                "collateralquantity": {
                    "type": "string"
                },
                "collateraltype": {
                    "type": "string"
                },
                "exchange": {
                    "type": "string"
                },
                "haircut": {
                    "type": "number"
                },
                "isin": {
                    "type": "string"
                },
                "product": {
                    "type": "string"
                },
                "profitandloss": {
                    "type": "number"
                },
                "quantity": {
                    "type": "number"
                },
                "realisedquantity": {
                    "type": "number"
                },
                "t1quantity": {
                    "type": "number"
                },
                "tradingsymbol": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "X-Token",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8000",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "User API",
	Description:      "API for managing users",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
